#!/usr/bin/env bash

set -e
cd "$(dirname $0)"/..


# find the installers and run them iteratively
# find . -name install.sh -not -path "./submodule/**/*"
find . -name install.sh -not -path "./submodule/**/*" | while read installer ; do sh -c "${installer}" ; done
